SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `identity` add CONSTRAINT identity_fk FOREIGN KEY (user_id)
REFERENCES users (userId) ON UPDATE CASCADE ON DELETE CASCADE;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `event_seats` add CONSTRAINT event_seats_fk FOREIGN KEY (event_id)
REFERENCES event_shows (eventId) ON UPDATE CASCADE ON DELETE CASCADE;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `model_mode` add CONSTRAINT model_mode_fk FOREIGN KEY (user_id)
REFERENCES users (userId) ON UPDATE CASCADE ON DELETE CASCADE;
SET FOREIGN_KEY_CHECKS=1;
